---
- name: Configure backend server
  hosts: tag_tf_backend_instance
  gather_facts: false
  become: true

  tasks:
    - name: Install required dependency
      package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Install docker engine
      package:
        name:
          - docker.io
        state: present

    - name: Manage docker services
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user | default(ansible_env.USER) }}"
        groups: docker
        append: yes

    - name: Loging to docker hub
      community.docker.docker_login:
        username: "{{ USERNAME }}"
        password: "{{ DOCKER_PASSWORD }}"

    - name: Start docker container
      docker_container:
        name: todo-backend
        image: "{{ USERNAME }}/todo-backend:staging-latest"
        state: started
        ports:
          - "5000:5000"
        env:
          MONGO_URI: "{{ MONGO_URI }}"
          PORT: "{{ PORT }}"
    