---
- name: Configure backend server
  hosts: tag_tf_backend_instance
  gather_facts: false
  become: true

  tasks:
    - name: Install required dependency
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: true

    - name: Install docker engine
      ansible.builtin.package:
        name:
          - docker.io
        state: present

    - name: Manage docker services
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user | default(ansible_env.USER) }}"
        groups: docker
        append: true

    - name: Loging to docker hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'USERNAME') }}"
        password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    - name: Ensure old staging image is absent
      community.docker.docker_image:
        name: "{{ lookup('env', 'USERNAME') }}/todo-backend:staging-latest"
        state: absent

    - name: Start docker container
      community.docker.docker_container:
        name: todo-backend
        image: "{{ lookup('env', 'USERNAME') }}/todo-backend:staging-latest"
        state: started
        ports:
          - "5000:5000"
        env:
          MONGO_URI: "{{ lookup('env', 'MONGO_URI') }}"
          PORT: "{{ lookup('env', 'PORT') }}"